import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface HistoryItem {
  id: string;
  timestamp: string;
  type: string;
  summary: string;
  details: any;
}

export const generatePDFReport = async () => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  let historyData: HistoryItem[] = [];
  try {
    const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';
    const res = await fetch(`${API_URL}/api/history`);
    const json = await res.json();
    if (json.success) {
      historyData = json.data;
    }
  } catch (e) {
    console.error("Failed to fetch history for report", e);
    alert("Could not fetch data for report");
    return;
  }

  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  doc.text("Wi-Fi Optimization Report", 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 28);
  doc.line(14, 32, pageWidth - 14, 32); 

  let currentY = 40;

  // --- SECTION 1: HEATMAPS ---
  const heatmaps = historyData.filter(h => h.type === 'heatmap' && h.details.snapshot);
  
  if (heatmaps.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("Coverage Heatmaps", 14, currentY);
    currentY += 10;

    heatmaps.slice(0, 3).forEach((map) => { 
      doc.setFontSize(11);
      doc.text(`${map.summary} (${new Date(map.timestamp).toLocaleDateString()})`, 14, currentY);
      currentY += 6;
      
      doc.setFontSize(9);
      doc.setTextColor(80);
      doc.text(`Avg Signal: ${map.details.avg_signal} dBm | Coverage: ${map.details.coverage_percent}%`, 14, currentY);
      currentY += 5;

      try {
        const imgProps = doc.getImageProperties(map.details.snapshot);
        const imgWidth = 120;
        const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
        
        if (currentY + imgHeight > 280) {
            doc.addPage();
            currentY = 20;
        }

        doc.addImage(map.details.snapshot, 'JPEG', 14, currentY, imgWidth, imgHeight);
        currentY += imgHeight + 15;
      } catch (err) {
        console.error("Image error", err);
      }
    });
  }

  if (currentY > 200) {
      doc.addPage();
      currentY = 20;
  }

  // --- SECTION 2: SCAN & HISTORY LOG (Таблиця) ---
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Event Log & Scan History", 14, currentY);
  currentY += 5;

  const tableBody = historyData.map(item => [
    new Date(item.timestamp).toLocaleString(),
    item.type.toUpperCase(),
    item.summary,
    item.type === 'scan' ? `${item.details.networks_count} nets found` : '-'
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [['Timestamp', 'Type', 'Summary', 'Details']],
    body: tableBody,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [59, 130, 246] },
  });

  // --- FOOTER ---
  const pageCount = doc.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 30, 290);
      doc.text("Generated by Wi-Fi Optimizer App", 14, 290);
  }

  doc.save(`WiFi_Report_${new Date().toISOString().slice(0,10)}.pdf`);
};